// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-kxoHPYJ1uqJtiwAMGkUz-9To6n7t74',
    appId: '1:722508102779:web:3128477b8f3bbb8df176de',
    messagingSenderId: '722508102779',
    projectId: 'les-fugitifs',
    authDomain: 'les-fugitifs.firebaseapp.com',
    storageBucket: 'les-fugitifs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vfPDa7UvDW0oatO7MnrfyWZFINFlGPU',
    appId: '1:722508102779:android:68bd2d70d9f9bb81f176de',
    messagingSenderId: '722508102779',
    projectId: 'les-fugitifs',
    storageBucket: 'les-fugitifs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcy-0V_Zqq_QkKAIoBFHPKfLY-24dHmpI',
    appId: '1:722508102779:ios:25b61a8b06b68652f176de',
    messagingSenderId: '722508102779',
    projectId: 'les-fugitifs',
    storageBucket: 'les-fugitifs.firebasestorage.app',
    iosBundleId: 'henigma.ch.intenebrisuno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcy-0V_Zqq_QkKAIoBFHPKfLY-24dHmpI',
    appId: '1:722508102779:ios:25b61a8b06b68652f176de',
    messagingSenderId: '722508102779',
    projectId: 'les-fugitifs',
    storageBucket: 'les-fugitifs.firebasestorage.app',
    iosBundleId: 'henigma.ch.intenebrisuno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-kxoHPYJ1uqJtiwAMGkUz-9To6n7t74',
    appId: '1:722508102779:web:67d1000984a59d96f176de',
    messagingSenderId: '722508102779',
    projectId: 'les-fugitifs',
    authDomain: 'les-fugitifs.firebaseapp.com',
    storageBucket: 'les-fugitifs.firebasestorage.app',
  );
}
